### ISSUE TITLE
Local cache config toggling causes exception

### ISSUE THREAD

**Issue by markfinal** [markfinal/cruiz#109]
This exception seen when toggling Configs in a local cache

```
Traceback (most recent call last):
  File "/Users/mark.final/dev/conan/library_env310/lib/python3.10/site-packages/cruiz/manage_local_cache/managelocalcachesdialog.py", line 725, in _config_toggle_printruncommands
    self._config_toggle(checked, ConanConfigBoolean.PRINT_RUN_COMMANDS)
  File "/Users/mark.final/dev/conan/library_env310/lib/python3.10/site-packages/cruiz/manage_local_cache/managelocalcachesdialog.py", line 715, in _config_toggle
    del self._modifications["Config"][config]
KeyError: 'Config'
```

**Comment by markfinal** [comment]
The problem here is the use of `isVisible()` on widgets to see if they're in use.

However, this is called _before_ its parent widget is visible, so it's forever returning false.
