### ISSUE TITLE
Cannot parse a recipe using a set for default_options

### ISSUE THREAD

**Issue by markfinal** [markfinal/cruiz#12]
Reported by a tester via email

With this recipe
```
from conans import ConanFile
 
class ConanComponent(ConanFile):
    name = "CruizTestComp"
    version = "1.0.0"

    options = {
        "build_with_interface": [True, False]
    }

    default_options = (
        "build_with_interface=False"
    )
```

has an incomplete UI (no options reported, no package_id reported), and this traceback on the console

```
Traceback (most recent call last):
  File "/Users/mark/dev/cruiz/cruiz-dev/cruiz/mainwindow.py", line 435, in load_recipe
    recipe_widget.post_init()
  File "/Users/mark/dev/cruiz/cruiz-dev/cruiz/recipe/recipewidget.py", line 328, in post_init
    self._load_configuration_dock(attributes)
  File "/Users/mark/dev/cruiz/cruiz-dev/cruiz/recipe/recipewidget.py", line 629, in _load_configuration_dock
    recipe_options = self._get_options_from_recipe(recipe_attributes)
  File "/Users/mark/dev/cruiz/cruiz-dev/cruiz/recipe/recipewidget.py", line 371, in _get_options_from_recipe
    (key, value, default_options[key] if default_options else None)
TypeError: string indices must be integers
```

Note that the `default_options` is a set. Conan documentation does suggest this attribute should be a Python dictionary. I believe earlier versions of Conan used non-dictionary types here.

However, Conan commands parse this, so cruiz should too.

```
(cruiz_env310) mark@Marks-MacBook-Air default_options_as_set % conan install conanfile.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.py (CruizTestComp/1.0.0): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (CruizTestComp/1.0.0): Generator txt created conanbuildinfo.txt
conanfile.py (CruizTestComp/1.0.0): Aggregating env generators
conanfile.py (CruizTestComp/1.0.0): Generated conaninfo.txt
conanfile.py (CruizTestComp/1.0.0): Generated graphinfo
```

**Comment by markfinal** [comment]
Found a failing case with this change, when there is an option of type ANY.

Example from GTest in Conan Center

TypeError: Don't know how to convert 'd' to type '<class 'str'>'

        "debug_postfix": ["ANY"],

        "debug_postfix": "d",
