### ISSUE TITLE
Detect a recipe without a name attribute and offer the user a chance to set it

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#145]
I noticed in recipes without a name attribute (as it's set procedurally on the CLI normally), that cruiz just renders it as "None".

In the same vein as the wizard to choose the version, perhaps a missing name can also be prompted for?

**Comment by foundry-markf** [comment]
Further, if you can see the console output (which you don't on Windows by default), then there is also this unhandled exception:

```
(library_env310) C:\Users\mark.final.FOUNDRY>python -m cruiz
ERROR:root:Updating toolbars suppressed: 'replace() argument 2 must be str, not None'
Traceback (most recent call last):
  File "C:\dev\cruiz\cruiz\recipe\recipewidget.py", line 573, in _update_toolbars
    self._ui.commandToolbar.refresh_action_shortcuts_and_tooltips(attributes)
  File "C:\dev\cruiz\cruiz\recipe\toolbars\command.py", line 208, in refresh_action_shortcuts_and_tooltips
    self._make_conan_install_params(recipe_attributes, None),
  File "C:\dev\cruiz\cruiz\recipe\toolbars\command.py", line 516, in _make_conan_install_params
    params = self._make_common_params(
  File "C:\dev\cruiz\cruiz\recipe\toolbars\command.py", line 463, in _make_common_params
    params.install_folder = recipe_widget.resolve_expression(install_folder)
  File "C:\dev\cruiz\cruiz\recipe\recipewidget.py", line 545, in resolve_expression
    expression = expression.replace(match, tokens[token])
TypeError: replace() argument 2 must be str, not None
```

which looks to be in reference to the missing name.
