### ISSUE TITLE
A recipe with no options gave an error

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#160]
Traceback (most recent call last):
  File "C:\dev\cruiz\src\cruiz\mainwindow.py", line 440, in load_recipe
    recipe_widget.post_init()
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 371, in post_init
    self._load_configuration_dock(attributes)
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 735, in _load_configuration_dock
    recipe_options = self._get_options_from_recipe(recipe_attributes)
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 424, in _get_options_from_recipe
    assert isinstance(
AssertionError: Expected default_options to be a dict

**Comment by foundry-markf** [comment]
Actually, this was incorrect.

This happened because of a faulty recipe that looked like this
```
    options = {"shared": [True]}
    default_options = {"shared"}
```
