### ISSUE TITLE
Incompatible Conan import in latest Conan 2

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#162]
```
Exception: No module named 'conans.client.cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/w/cruiz/src/cruiz/manage_local_cache/managelocalcachesdialog.py", line 431, in _save_modifications
    self._context.remotes_sync(self._ui.remotesTable.remotes_list())
  File "/w/cruiz/src/cruiz/commands/context.py", line 308, in remotes_sync
    raise Exception("Sync remotes failed") from exception
Exception: Sync remotes failed
```

This was seen with Conan 2.7.1

**Comment by markfinal** [comment]
Issues confirmed with Conan v2.9.2

In the remote browser, clicking on a recipe revision shows
```
Traceback (most recent call last):
  File "/Users/mark/dev/cruiz/cruiz-dev/src/cruiz/workers/api/v2/reciperevisions.py", line 35, in invoke
    app = ConanApp(api.cache_folder, api.config.global_conf)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

Confirmed the original error, when in the Manage Local Caches dialog, on a Conan 2 cache, go to the Remotes tab, uncheck an enabled field, and then click Apply

```
Exception: No module named 'conans.client.cache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mark/dev/cruiz/cruiz-dev/src/cruiz/manage_local_cache/managelocalcachesdialog.py", line 431, in _save_modifications
    self._context.remotes_sync(self._ui.remotesTable.remotes_list())
  File "/Users/mark/dev/cruiz/cruiz-dev/src/cruiz/commands/context.py", line 308, in remotes_sync
    raise Exception("Sync remotes failed") from exception
Exception: Sync remotes failed
```

**Comment by markfinal** [comment]
It may be worth regressing back to find the original change, as there may be hints on how to progress.

**Comment by markfinal** [comment]
Version 2.1.0 introduced the change.

This was one of them: https://github.com/conan-io/conan/commit/f7fceca3717d755d796e8c733698c0fb455ed62e

for the remote browser

**Comment by markfinal** [comment]
A refactor of the RemotesAPI seems to be the start of the next issue

https://github.com/conan-io/conan/commit/fa991f3aec513f7346e28fc5690c41b429bafcc3
