### ISSUE TITLE
Options: don't separate by semi-colon

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#170]
Although I know that the options to a recipe in the configuration are comma separated, I accidentally put a semi-colon in, and got this error

```
ERROR:root:Updating toolbars suppressed: 'too many values to unpack (expected 2)'
Traceback (most recent call last):
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 573, in _update_toolbars
    self._ui.commandToolbar.refresh_action_shortcuts_and_tooltips(attributes)
  File "C:\dev\cruiz\src\cruiz\recipe\toolbars\command.py", line 196, in refresh_action_shortcuts_and_tooltips
    self._make_conan_create_params(recipe_attributes, None),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\cruiz\src\cruiz\recipe\toolbars\command.py", line 501, in _make_conan_create_params
    params = self._make_common_params(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\cruiz\src\cruiz\recipe\toolbars\command.py", line 442, in _make_common_params
    option_name, option_value = keyvalue.split("=")
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\dev\cruiz\src\cruiz\mainwindow.py", line 440, in load_recipe
    recipe_widget.post_init()
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 372, in post_init
    self._generate_dependency_graph(attributes)
  File "C:\dev\cruiz\src\cruiz\recipe\recipewidget.py", line 1117, in _generate_dependency_graph
    option_name, option_value = keyvalue.split("=")
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

Thankfully the UI hadn't locked up, and I could correct it.

**Comment by foundry-markf** [comment]
However, I did have to restart cruiz to get the commands functioning.

**Comment by markfinal** [comment]
This turns out not to be the regex's fault, but how the value is split.

If you have an expression
```
a:b=c;d:e=f
```
then the unlimited split in the stacktrace above fails because there are multiple equal signs.
