### ISSUE TITLE
Error from PySide 6 when running on Ubuntu ARM 24.04

### ISSUE THREAD

**Issue by markfinal** [markfinal/cruiz#174]
```
/home/parallels/dev/cruiz/.venv312/lib/python3.12/site-packages/PySide6/Qt/libexec/rcc: error while loading shared libraries: libdouble-conversion.so.3: cannot open shared object file: No such file or directory
```

This is PySide 6.6.3.

**Comment by markfinal** [comment]
This got me further
```
sudo apt install libdouble-conversion3
```

Running `python -m cruiz` now gives

```
(.venv312) parallels@ubuntu-linux-2404:~/dev/cruiz/cruiz-dev$ python -m cruiz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/__main__.py", line 17, in <module>
    from cruiz.entrypoint import main  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/entrypoint.py", line 40, in <module>
    from cruiz.mainwindow import MainWindow  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/mainwindow.py", line 53, in <module>
    from cruiz.remote_browser.remotebrowser import RemoteBrowserDock
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/remotebrowser.py", line 12, in <module>
    from cruiz.pyside6.remote_browser import Ui_remotebrowser
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/pyside6/remote_browser.py", line 25, in <module>
    from cruiz.remote_browser.pages.packagebinarypage import PackageBinaryPage
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/pages/packagebinarypage.py", line 18, in <module>
    from qtpy import QtWebEngineCore
  File "/home/parallels/dev/cruiz/.venv312/lib/python3.12/site-packages/qtpy/QtWebEngineCore.py", line 37, in <module>
    from PySide6.QtWebEngineCore import *
ImportError: libwebp.so.6: cannot open shared object file: No such file or directory

```

**Comment by markfinal** [comment]
The downside from the above is that Ubuntu 24.04 only provides
```
/usr/lib/aarch64-linux-gnu/libwebp.so.7
```
This is a potential workaround
```
pushd /usr/lib/aarch64-linux-gnu
sudo ln -s libwebp.so.7 libwebp.so.6
```
(unconfirmed)

**Comment by markfinal** [comment]
Next up is
```
(.venv312) parallels@ubuntu-linux-2404:~/dev/cruiz/cruiz-dev$ python -m cruiz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/__main__.py", line 17, in <module>
    from cruiz.entrypoint import main  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/entrypoint.py", line 40, in <module>
    from cruiz.mainwindow import MainWindow  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/mainwindow.py", line 53, in <module>
    from cruiz.remote_browser.remotebrowser import RemoteBrowserDock
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/remotebrowser.py", line 12, in <module>
    from cruiz.pyside6.remote_browser import Ui_remotebrowser
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/pyside6/remote_browser.py", line 25, in <module>
    from cruiz.remote_browser.pages.packagebinarypage import PackageBinaryPage
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/pages/packagebinarypage.py", line 18, in <module>
    from qtpy import QtWebEngineCore
  File "/home/parallels/dev/cruiz/.venv312/lib/python3.12/site-packages/qtpy/QtWebEngineCore.py", line 37, in <module>
    from PySide6.QtWebEngineCore import *
ImportError: libminizip.so.1: cannot open shared object file: No such file or directory
```
which is sorted by
```
sudo apt install libminizip1t64
```

**Comment by markfinal** [comment]
Next up is
```
(.venv312) parallels@ubuntu-linux-2404:~/dev/cruiz/cruiz-dev$ python -m cruiz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/__main__.py", line 17, in <module>
    from cruiz.entrypoint import main  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/entrypoint.py", line 40, in <module>
    from cruiz.mainwindow import MainWindow  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/mainwindow.py", line 53, in <module>
    from cruiz.remote_browser.remotebrowser import RemoteBrowserDock
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/remotebrowser.py", line 12, in <module>
    from cruiz.pyside6.remote_browser import Ui_remotebrowser
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/pyside6/remote_browser.py", line 25, in <module>
    from cruiz.remote_browser.pages.packagebinarypage import PackageBinaryPage
  File "/home/parallels/dev/cruiz/cruiz-dev/src/cruiz/remote_browser/pages/packagebinarypage.py", line 18, in <module>
    from qtpy import QtWebEngineCore
  File "/home/parallels/dev/cruiz/.venv312/lib/python3.12/site-packages/qtpy/QtWebEngineCore.py", line 37, in <module>
    from PySide6.QtWebEngineCore import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
```
again provided by an earlier version
```
(.venv312) parallels@ubuntu-linux-2404:~/dev/cruiz/cruiz-dev$ find /usr -name libtiff*
/usr/lib/aarch64-linux-gnu/libtiff.so.6
/usr/lib/aarch64-linux-gnu/evince/4/backends/libtiffdocument.so
/usr/lib/aarch64-linux-gnu/libtiff.so.6.0.1
/usr/share/doc/libtiff6
```
which might be worked around with
```
pushd /usr/lib/aarch64-linux-gnu/
sudo ln -s libtiff.so.6 libtiff.so.5
```

**Comment by markfinal** [comment]
At this point, cruiz does start.
