### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by DoDoENT** [markfinal/cruiz#8]
OS: MacOS 12.6 on Apple Silicon (M1Pro)
Python: 3.10.6 from Homebrew

When starting `cruiz`, I get the following output: 
```
$ cruiz
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/psutil/_psosx.py", line 401, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/cruiz", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/cruiz/entrypoint.py", line 138, in main
    window = MainWindow()
  File "/opt/homebrew/lib/python3.10/site-packages/cruiz/mainwindow.py", line 197, in __init__
    self._configure_ssh_agent_statusbar()
  File "/opt/homebrew/lib/python3.10/site-packages/cruiz/mainwindow.py", line 270, in _configure_ssh_agent_statusbar
    if "ssh-agent" in process.name():
  File "/opt/homebrew/lib/python3.10/site-packages/psutil/__init__.py", line 628, in name
    cmdline = self.cmdline()
  File "/opt/homebrew/lib/python3.10/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.10/site-packages/psutil/_psosx.py", line 348, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=1100)
```

And then the app just hangs - no GUI is displayed.

**Comment by DoDoENT** [comment]
Same thing if I try running from clean `virtualenv`.

**Comment by markfinal** [comment]
Thanks for the report.

This is failing in the code that is asking if an SSH agent is running, in order to populate the main window status bar.

The code loops over all running processes (via psutils) asking to see if ssh-agent is running by name. That's the part that looks like it's failing. It's almost like there are some short-lived processes, that have been closed between finding their pid, and querying about them.

I've not seen this particular failure before, so need to try to reproduce myself. Although I have an idea for a band-aid.

**Comment by markfinal** [comment]
Not had any luck in reproducing, so used some advice from psutils docs to work around.

Would you mind trying a development build to see if it helps?

* Git clone this repo
* Checkout the branch `mf/issue8_ignore_no_such_process_psutils_for_sshagent`
* `pip install -e .`
* `cruiz`

Thanks

**Comment by DoDoENT** [comment]
It works from your branch.

But it doesn't play very nice with Apple's dark theme

![image](https://user-images.githubusercontent.com/158844/196173511-b5d0ba18-b968-4dea-8345-64cab24fb2ed.png)

Thank you for the quick fix!

**Comment by markfinal** [comment]
Themes are definitely something on the TODO list to make it a nicer experience.

There's a dark theme (from another pip package) that is semi-good but application specific in the preferences dialog.

I need some more knowledge on how to make Qt play nice with the OS choice.

I'll roll this fix into a patch release now. Thanks for testing.
